/**
 * @description       : This handles the platform events generated by TIBCO for Connected Customer Feature
 * @author            : Sreenish Krishnan
 * @domain            : Connected Customer
 * @last modified on  : 07-22-2022
 * @last modified by  : Sreenish Krishnan
 **/
trigger CustomerDataSyncEventTrigger on CustomerDataSync__e(after insert) {
	
    CustomerDataSyncEventTriggerHandler.execute();

}
