/**************************************************
Description:    Trigger for Platform Event that is generated by Camunda and picked up in Apex.
                    BAMExternalOnboardingEventHandler_Test implicitly covers this class
History:
--------------------------------------------------
2019-09-30  nathan.franklin@auspost.com.au  Updated
**************************************************/
trigger ExternalOnboardingEventTrigger on ExternalOnboardingEvent__e (after insert) {
    ExternalOnboardingEventTriggerHandler.execute();
}