/***
 * @author Steve L.
 * @date 2023-07-15
 * @group Tests
 * @tag Selector
 * @tag SObjects that can be part of Related To field
 * @domain Core
 * @description Test Class covering EventSelector
 * @changelog
 * 2023-07-15- Steve L - Created
 */

@IsTest
private class RelatedTosSelector_Test {
    /**
	 * Test:
	 *  This class does not support querying, so at most, any tests that we write would simply be testing the parent ApplicationSelector class which is pointless
	 *  This test will simply cover the code so the class is deployable
	 */
    @IsTest
    public static void testCoverCode() {

        // =====================================
        // Data Preparation
        // =====================================
        // None!

        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();
        System.assert(true, 'Something went wrong');
        Test.stopTest();
    }
}