/**
 ** Description: Depot Calculation
 ** Author: David Catindoy(CloudSherpas)
 ** Date Created: OCT.9.2015
 ** History:--------------------------------------------
 **         OCT.9.2015 David Catindoy - Created
 **/
public class StarTrackDepotCalculation {
    
    @InvocableMethod
    public static void depotCalculation(List<Id> consignmentIds){
        //unused class
        //StarTrackUtil.calculateDepot(consignmentIds);        
    }
}